name: Run Liquibase Migration
on:
  push:
    branches: [ main, master ]
jobs:
  liquibase:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Run Liquibase Update
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/liquibase/changelog \
          liquibase/liquibase:4.24.0 \
          --changeLogFile=changelog.yaml \
          --url="jdbc:sqlserver://${{ secrets.DB_URL }}:1433;databaseName=poc;encrypt=true;trustServerCertificate=true" \
          --username=${{ secrets.DB_USERNAME }} \
          --password=${{ secrets.DB_PASSWORD }} \
          update
